apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-product
  template:
    metadata:
      labels:
        app: app-product
    spec:
      containers:
        - name: app-product
          image: 590989737979.dkr.ecr.us-east-1.amazonaws.com/application-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-product-config
            - secretRef:
                name: db-product-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
